version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
    networks:
      - big-data-network

  airflow:
    image: apache/airflow:latest
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - cassandra
    networks:
      - big-data-network
    command: >
      bash -c "
      airflow db init &&
      airflow scheduler
      "

  python_app:
    image: python:3.8-slim
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - cassandra
      - airflow
    networks:
      - big-data-network
    command: python3 app.py

networks:
  big-data-network:
    driver: bridge